server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://localhost:8081
          predicates: [ Path=/products/** ]
        - id: order
          uri: http://localhost:8082
          predicates: [ Path=/orders/** ]
        - id: inventory
          uri: http://localhost:8083
          predicates: [ Path=/inventory/** ]
        - id: catalog
          uri: http://localhost:8084
          predicates: [ Path=/catalog/** ]
