spring:
  application.name: stream-processor
  kafka:
    bootstrap-servers: localhost:9092
management:
  endpoints.web.exposure.include: health,info,prometheus
app:
  topics:
    ordersCreated: orders.created
    ordersEnriched: orders.enriched
