server:
  port: 8082
spring:
  application.name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
springdoc:
  api-docs.enabled: true
  swagger-ui.path: /swagger
management:
  endpoints.web.exposure.include: health,info,prometheus
app:
  topics:
    ordersCreated: orders.created
