server:
  port: 8081
spring:
  application.name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shopdb
    username: shop
    password: shop
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false
springdoc:
  api-docs.enabled: true
  swagger-ui.path: /swagger
management:
  endpoints.web.exposure.include: health,info,prometheus
