server:
  port: 8083
spring:
  application.name: inventory-service
  cache.type: redis
  data:
    redis:
      host: localhost
      port: 6379
springdoc:
  api-docs.enabled: true
  swagger-ui.path: /swagger
management:
  endpoints.web.exposure.include: health,info,prometheus
